baseURL: "https://bengoehring.github.io" 
title: Ben Goehring
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Vitae
          url: goehring-cv-new-format.pdf
          weight: 3

params:
    description: ""
    author: Ben Goehring
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    body_classes: "baskerville"
    profileMode:
          enabled: true
          title: "Ben Goehring"
          subtitle: "Hello! I am a PhD Candidate in political science and public policy at the University of Michigan. I am interested in bureaucracies, the presidency, and state politics. In my dissertation, I link personnel records of twenty U.S. states’ employees with voter registration files to document, for the first time, the partisan composition of U.S. state workforces. I utilize this data to examine whether removing civil service protections for government employees increases the likelihood of outpartisan bureaucrats losing their jobs. <br /><br />I graduated from George Washington University in 2017 with degrees in philosophy and political science. After college, I worked as a research assistant at the Urban Institute studying means-based social assistance programs."
          imageUrl: "ben-goehring-3.jpg"
          imageWidth: 250
          imageHeight: 300
          imageTitle: Ben Goehring
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Vitae
              url: goehring-cv-new-format.pdf

    socialIcons:
        - name: Email
          url: mailto:bengoehr@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=08m0WM0AAAAJ&hl=en&oi=ao

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ben Goehring"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2