baseURL: "https://bengoehring.github.io" 
title: Ben Goehring
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Vitae
          url: goehring-cv-new-format.pdf
          weight: 3

params:
    description: ""
    author: Ben Goehring
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    body_classes: "Lato"
    sharing_image: "favicon.ico" 
    profileMode:
          enabled: true
          title: "Hi! I'm Ben Goehring." #
          subtitle: "I am a PhD Candidate in political science and public policy at the University of Michigan. In 2025, I will start as an Assistant Professor of Public Policy at the Frank Batten School of Leadership and Public Policy at the University of Virginia. My <a href='research/index.html'>research</a> investigates the staffing, oversight, and control of government agencies. In my <a href='jmp.pdf'>job market paper</a>, I link longitudinal personnel records of nearly all public employees in twenty U.S. states with voter registration files to examine whether governors try to remove political opponents from the workforce after the passage of policies that make it easier to fire bureaucrats. Other projects investigate how different types of legislative oversight influence nursing home inspections <a href= 'bsgs.pdf'>(under review)</a> and the role of the public in checking unilateral presidential actions <a href = 'public-responses-to-unilateral-policymaking.pdf'>(published in JEPS)</a>.

          <br /><br /> I have helped <a href='teaching/index.html'>teach</a> a number courses at the graduate and undergraduate levels, including research design and a seminar for students writing their honors theses. I have also twice served as the instructor of record for our department's three-week math camp for incoming PhD students. My teaching was recognized by the department in 2022 with the John W. Kingdon Award for Outstanding Teaching. I also enjoy incorporating undergraduates into active research projects. I have <a href='improving-content-analysis-tools-for-working-with-undergraduate-research-assistants.pdf'>published</a> best practices for training and managing undergraduate research assistants, developed an <a href='https://cran.r-project.org/web/packages/ura/index.html'>R package</a> to help other researchers supervise their teams, and received the university's Undergraduate Research Opportunity Program's Outstanding Research Mentor Award.

          <br /><br />I am originally from Fargo, North Dakota and graduated from George Washington University in 2017 with degrees in philosophy and political science. Before graduate school, I studied means-tested social assistance programs as a research assistant at the Urban Institute. I co-authored a couple of reports (<a href='https://www.urban.org/research/publication/welfare-rules-databook-state-tanf-policies-july-2017'>here</a>, and <a href='https://www.urban.org/research/publication/welfare-rules-databook-state-tanf-policies-july-2018'>here</a>) on states' Temporary Assistance for Needy Families' policies and helped maintain the <a href='https://boreas.urban.org/T3Welcome.php'>TRIM3 microsimulation model</a>."
          imageUrl: "Goehring-2024-3.jpg"
          imageWidth: 350
          imageHeight: 350
          imageTitle: Ben Goehring
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Vitae
              url: goehring-cv-new-format.pdf

    socialIcons:
        - name: Email
          url: mailto:bengoehr@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=08m0WM0AAAAJ&hl=en&oi=ao

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ben Goehring"
      #icon: favicon.ico
      #iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2