baseURL: "https://bengoehring.github.io" 
title: Ben Goehring
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Vitae
          url: goehring-cv.pdf
          weight: 3

params:
    description: ""
    author: Ben Goehring
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    body_classes: "Lato"
    sharing_image: "favicon.ico" 
    profileMode:
          enabled: true
          title: "Hi! I'm Ben Goehring." #
          subtitle: "In Fall 2025, I will start as an Assistant Professor of Public Policy at the Frank Batten School of Leadership and Public Policy at the University of Virginia. I study American political institutions, with a particular focus on executive branch politics at the state and federal levels. I am also interested in the causes of public sector turnover, especially among correctional officers.

          <br /><br />I am originally from Fargo, North Dakota and graduated from George Washington University in 2017 with degrees in philosophy and political science. Before graduate school, I studied means-tested social assistance programs as a research assistant at the Urban Institute. I co-authored a couple of reports (<a href='https://www.urban.org/research/publication/welfare-rules-databook-state-tanf-policies-july-2017'>here</a>, and <a href='https://www.urban.org/research/publication/welfare-rules-databook-state-tanf-policies-july-2018'>here</a>) on states' Temporary Assistance for Needy Families' policies and helped maintain the <a href='https://boreas.urban.org/T3Welcome.php'>TRIM3 microsimulation model</a>."
          imageUrl: "Goehring-2024-3.jpg"
          imageWidth: 350
          imageHeight: 350
          imageTitle: Ben Goehring
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Vitae
              url: goehring-cv.pdf

    socialIcons:
        - name: Email
          url: mailto:gde9rc@virginia.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=08m0WM0AAAAJ&hl=en&oi=ao

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ben Goehring"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2