baseURL: "https://bengoehring.github.io" 
title: Ben Goehring
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Vitae
          url: goehring-cv.pdf
          weight: 3

params:
    description: ""
    author: Ben Goehring
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    body_classes: "Lato"
    sharing_image: "favicon.ico" 
    profileMode:
          enabled: true
          title: "Hi! I'm Ben Goehring." #
          subtitle: "I am an Assistant Professor of Public Policy and Politics at the Frank Batten School of Leadership and Public Policy and (by courtesy) the Department of Politics at the University of Virginia. I study American political institutions, with a particular focus on executive branch politics at the state and federal levels. I am also interested in the causes of public sector turnover, especially among correctional officers.

          <br /><br />I received my PhD in political science and public policy in 2025 from the University of Michigan. Before graduate school, I studied means-tested social assistance programs at the Urban Institute."
          imageUrl: "Goehring-2024-3.jpg"
          imageWidth: 350
          imageHeight: 350
          imageTitle: Ben Goehring
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Vitae
              url: goehring-cv.pdf

    socialIcons:
        - name: Email
          url: mailto:goehring@virginia.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=08m0WM0AAAAJ&hl=en&oi=ao
        - name: web of science
          url: https://www.webofscience.com/wos/author/record/NLO-5450-2025

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ben Goehring"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2